
# ===================================================================================
# config.yml 　The MIT License　(c)2019 econosys system  https://econosys-system.com/
# ===================================================================================


# ====================================================================
# メールの設定
# ====================================================================

# 担当者設定
site_name        : 【テスト会社名】                       # メール送信者（ユーザーへのメールの送信者）
site_to          : aaa@bbb.ccc.ddd                      # お問い合わせフォーム受信担当者メールアドレス
site_cc          :                                      # 担当者CC
site_bcc         :                                      # 担当者BCC
site_subject     : ホームページよりお問い合わせがありました  # 担当者向けメールのタイトル
site_replyto     :                                      # 返信先を別アドレスに設定したい時（通常は設定しなくてOK）


# ユーザー設定
user_subject : お問い合わせありがとうございます | 【テスト会社名】   # お客様向けメールのタイトル


# メール送信方式 (mail または smtp)
mail_method : mail

# SMTP（メール送信サーバ）設定（メール送信方式が smtp の時に必要）
SMTP_host  : yyyyy.zzz
SMTP_port  : 587
SMTP_user  : xxxxx@yyyyy.zzz
SMTP_pass  : MY_PASSWORD

# メール送信完了画面（メール送信後この画面にリダイレクトします。）
end_html   : php_mailform_end.html



# テンプレート設定

# 生成されるHTMLは↓の構成になります（id, class は任意の値を指定できます。）
#
# <form id="XXXXX" class="YYYYY">
#   <div class="DDDDD">
#      <ul class="UUUUU">
#         <li class="LLLLL">
#           <div class="LTLTLT"><span>お名前</span></div>
#           <div class="LDLDLD"><input type="text" name="name" placeholder="お名前　太郎"></div>
#         </li>
#         <li class="LLLLL">
#           <div class="LTLTLT"><span>電話番号</span></div>
#           <div class="LDLDLD"><input type="text" name="tel" placeholder="000-111-2222"></div>
#         </li>
#      </ul>
#   </div>
# </form>

form_id_name          : form_contact          # <form id="XXXXX" class="YYYYY"> のID名
form_class_name       : h-adr                 # <form id="XXXXX" class="YYYYY"> のクラス名

div_class_name        : contents__form_back   # <div class="DDDDD">のクラス名
ul_class_name         : contents__form_list clearfix   # <ul class="UUUUU">のクラス名
li_class_name         : row                   # <li class="LLLLL">のクラス名
row1_class_name       : col-xs-12 col-sm-4    # <div class="LTLTLT">のクラス名
row2_class_name       : col-xs-12 col-sm-8    # <div class="LDLDLD">のクラス名


template_file_input   : mail_form.html          # テンプレートファイル名（入力画面）
template_file_confirm : mail_form_confirm.html  # テンプレートファイル名（確認画面）

tmp_dir               : tmp                   # アップロードファイルを一時処理するディレクトリ

# ====================================================================
# JavaScriptの設定
# ====================================================================
yubinbango_js   : true                  # trueの時【郵便番号→住所自動変換ライブラリ】Yubinbango.js を読み込みます。
beforeunload_js : true                  # trueの時「入力エリアに文字が残っている時に画面遷移しようとした時にアラートを表示」します


# ====================================================================
# フォームの設定 （先頭の form : は変更しないこと）（インデントは同じようにつけること）（タブは使用せずスペースでインデントすること）
# ====================================================================

# ====================================================================
# 必須入力項目（任意入力項目）について
# ====================================================================
# 以下のような設定項目（NOT_BLANK , CHECKBOX_NOT_BLANK）があると、入力必須項目となります。
# 任意入力項目にしたい場合はこの行を（行ごと）削除して下さい
#
# validate   :
#      NOT_BLANK  : お名前を入力してください。
# (↑ この上の1行を削除すると任意入力項目となります)
#
#

form :

  name :
    title_mail : お名前
    title_html : お名前 ※
    placeholder: 問い合わせ　太郎
    input_type : text # text, number, email, tel, password, select, checkbox, textarea, radio, file から選択。未指定時は「text」
    validate   :
      NOT_BLANK  : お名前を入力してください。

  email :
    title_mail : メールアドレス
    title_html : メールアドレス ※
    placeholder: user@server.xxx
    input_type : email # text, number, email, tel, password, select, checkbox, textarea, radio, file から選択。未指定時は「text」
    validate   :
      NOT_BLANK   : メールアドレスを入力してください。
      EMAIL       : メールアドレスの形式が正しくありません。

  postal :
    title_mail : 郵便番号
    title_html : 郵便番号
    placeholder: 123-4567
    class      : p-postal-code
    input_type : number # text, number, email, tel, password, select, checkbox, textarea, radio, file から選択。未指定時は「text」
    validate   :
      REGEX,^[0-9\-０-９−―-]+$ : 郵便番号を正しく入力してください。

  address :
    title_mail : 住所
    title_html : 住所
    placeholder: 住所
    class      : p-region p-locality p-street-address p-extended-address
    input_type : text # text, number, email, tel, password, select, checkbox, textarea, radio, file から選択。未指定時は「text」
    validate   :
      REGEX,[一-龠]+ : 住所には漢字が1文字以上含まれている必要があります

  tel :
    title_mail : 電話番号
    title_html : 電話番号
    placeholder: 000-111-2222
    input_type : tel # text, number, email, tel, password, select, checkbox, textarea, radio, file から選択。未指定時は「text」
    validate   :
      REGEX,^[0-9\-０-９−―-]+$ : 電話番号を正しく入力してください。

  otoiawase_a :
    title_mail  : お問合せの種類
    title_html  : お問合せの種類
    input_type  : radio    # text, number, email, tel, password, select, checkbox, textarea, radio, file から選択。未指定時は「text」
    input_values:
      -
        name  : 種類 1
        value : 種類 1
      -
        name  : 種類 2
        value : 種類 2
      -
        name  : 種類 3
        value : 種類 3
      -
        name  : 種類 4
        value : 種類 4
    validate:
      CHECKBOX_NOT_BLANK: お問合せの種類を選択してください。

  otoiawase_b :
    title_mail : お問合せ内容
    title_html : お問合せ内容
    placeholder: お問合せ内容を詳しくお書きください。
    input_type : textarea    # text, number, email, tel, password, select, checkbox, textarea, radio, file から選択。未指定時は「text」
    validate   :
        NOT_BLANK : お問合せ内容2を入力してください。

  my_attach :
    title_mail: 添付ファイル
    title_html: 添付ファイル
    placeholder: ファイルを選択
    input_type: file    # text, number, email, tel, password, select, checkbox, textarea, radio, file から選択。未指定時は「text」
    validate  :






# ====================================================================
# システム設定（これより下は変更しないで下さい）
# ====================================================================

# データベースへの自動接続をするか？
dbAutoConnect: false
# データベースの文字コードを「utf8」「ujis」「sjis」から選択（PHPスクリプト文字コードと合わせること）
dbDefaultCharacterSet: utf8
# PHPスクリプト文字コード 「SJIS」「EUC-JP」「UTF-8」から選択
script_encoding: UTF-8
# 出力するhtmlの文字コード「SJIS」「EUC-JP」「UTF-8」から選択
output_encoding: UTF-8
# HTTPヘッダの charset で指定する文字コード「SJIS」「EUC-JP」「UTF-8」から選択。または指定しない場合はPHPのデフォルトとなる
httpheader_encoding: UTF-8

# エラー出力設定【1】全てのエラーを出力  【0】通知エラー以外の全てのエラーを出力  【-1】通知エラー警告エラー以外の全てのエラーを出力
# ここのエラー設定で /var/log/httpd/.... のエラーログにも出力されなくなるので注意
errorReporting: 0

